version: '3'

services:
  notification-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-notification-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./logs:/app/logs